#!/bin/sh 

#   concat_bvars - script to concatenate .bvars file that are output from 
#   "first". The script retains a single header and keeps track of the number 
#   subjects. All bvars should correspond to the same model.  
#
#   Brian Patenaude and Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2009 University of Oxford
#
#   SHCOPYRIGHT

Usage() {
    echo ""
    echo "Usage:   concat_bvars <output_bvars.bvars> <list_of_input_bvars>"
    echo ""
    echo "e.g.:  concat_bvars lhipp_all.bvars sub1_lhipp.bvars sub2_lhipp.bvars ... subN_lhipp.bvars"
    echo ""
}

Usage_and_exit() {
    Usage
    exit
}

[ "${1}_" = "_"  ] && Usage_and_exit

output=$1;
shift;
#echo "make sure all bvar files use the same model!!!!"

if [ -f $output ] ; then
    Usage
    echo " "
    echo "ERROR: Output file already exists!"
    echo "Check the above usage and, if necssary, remove this file before running"
    exit 1
fi

listfile=`$FSLDIR/bin/tmpnam`_bvars
if [ -f ${listfile}.txt ] ; then rm -f ${listfile}.txt ; fi
touch ${listfile}.txt
for fn in $@ ; do
  echo $fn >> ${listfile}.txt
done
$FSLDIR/bin/first_utils --concatBvars -i ${listfile}.txt -o $output
rm -f ${listfile}.txt
