#!/bin/sh

#   first_roi_slicesdir - script to view slicesdir on a region of interest
#   defined by a set of label images (e.g. output of FIRST). A set of 
#   temporary roi images are created, slicesdir is then run on those.
#
#   Brian Patenaude and Matthew Webster, FMRIB Image Analysis Group
#
#   Copyright (C) 2006-2010 University of Oxford
#
#   SHCOPYRIGHT

Usage() {
    echo ""
    echo "Usage:   first_roi_slicesdir  <input_t1_images> <input_label_images>"
    echo ""
    echo "e.g.:  first_roi_slicesdir *_t1.nii.gz *_L_Hipp_first.nii.gz "
    echo ""
    exit
}

[ "${1}_" = "_"  ] && Usage

num=$#
echo "total number of image: " $num
num=`echo "${num}/2 " | bc`
echo "number of image pairs: " $num

#this loop creates the paired list  
i=1;
while [ $i -le ${num} ] ; do 

    pout=`echo $@ | awk '{ print $'$i' }'`
    
    imind=`echo ${i} + ${num} | bc`
    imlb=`echo $@ | awk '{ print $'$imind' }'`
      imlbout=`echo $imlb | awk -F / '{ print $NF }'`
      imlbout=`remove_ext $imlbout `

    roi=`${FSLDIR}/bin/fslstats $imlb -w` 

    xmin=`echo $roi | awk '{ print $1 }'`
    xsize=`echo $roi | awk '{ print $2 }'`
    xmin=`echo $xmin - 10 | bc`
    xsize=`echo $xsize + 20 | bc`

    
    ymin=`echo $roi | awk '{ print $3 }'`
    ysize=`echo $roi | awk '{ print $4 }'`
    ymin=`echo $ymin - 10 | bc`
    ysize=`echo $ysize + 20 | bc`
 
    zmin=`echo $roi | awk '{ print $5 }'`
    zsize=`echo $roi | awk '{ print $6 }'`
    zmin=`echo $zmin - 10 | bc`
    zsize=`echo $zsize + 20 | bc`

    roi="${xmin} $xsize $ymin $ysize $zmin $zsize 0 1"

    pout=`remove_ext $pout`
    imlb=`remove_ext $imlb`
    
    pout2=`echo $pout | awk -F / '{ print $NF }'`
    pout2=`remove_ext $pout2`
    echo $i $pout2

    ${FSLDIR}/bin/fslroi $pout ${pout2}_t1grot${i} $roi
    ${FSLDIR}/bin/fslroi $imlb ${imlbout}lbgrot${i} $roi
    pairlist=${pairlist}" "${pout2}_t1grot${i}" "${imlbout}lbgrot${i}
   
    i=$((i+1)); 
done

echo "run slicesdir"
${FSLDIR}/bin/slicesdir -o -e -1 ${pairlist}

#remove tmeporrary images

echo "removing files..."
for i in $pairlist; do 
    echo $i; 
   ${FSLDIR}/bin/imrm $i; 
done


