#!/bin/sh

#   surface_fdr - runs FDR correction on a FIRST surface (from vertex analysis)
#
#   Mark Jenkinson, FMRIB Image Analysis Group
#
#   Copyright (C) 2008-2009 University of Oxford
#
#   SHCOPYRIGHT


if [ $# -lt 1 ] ; then
  echo "Usage: `basename $0` <input_vtk>"
  echo "         where input_vtk is the vertex analysis vtk output"
  echo "         Outputs are *_pvals.vtk  *_Fthresh.vtk and some nifti images"
  echo "          (using the input vtk filename as the basename for output files)"
#  echo "       For FSL4.1.2 or before:"
#  echo "       `basename $0` <input vtk> <dof> <dof2>"
#  echo "         For the second usage the two Degrees Of Freedom for the" 
#  echo "         F-stats are specified directly."
#  echo "         (NB: these are stored in the vtk file for FSL4.1.3 and later)"
  exit 1
fi

infile=`echo $1 | sed 's/.vtk$//'`;

if [ $# -ge 3 ] ; then
    dof=$2
    dof2=$3
elif [ $# -eq 2 ] ; then
    txtfile=$2
    dof=`cat ${txtfile} | grep -i pillai | head -1 | awk '{ print $5 }'`;
    dof2=`cat ${txtfile} | grep -i pillai | head -1 | awk '{ print $6 }'`;
    echo "Degrees of freedom are: $dof $dof2"
fi
if [ $# -ge 2 ] ; then
  dofopts="--dof=$dof --dof2=$dof2"
else
  dofopts=""
fi

$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -o ${infile}_Fvals --doScalarsToVolume
$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -o ${infile}_pvals.vtk --doFtoP $dofopts
$FSLDIR/bin/run_mesh_utils -m ${infile}_pvals.vtk -o ${infile}_pvals --doScalarsToVolume
thr=`$FSLDIR/bin/fdr -i ${infile}_pvals -q 0.05 | grep -v '^ *[A-Za-z]'`;
echo "FDR threshold is $thr"
$FSLDIR/bin/fslmaths ${infile}_pvals -uthr $thr -bin ${infile}_fdrmask
$FSLDIR/bin/fslmaths ${infile}_pvals -mas ${infile}_fdrmask ${infile}_pthresh
$FSLDIR/bin/fslmaths ${infile}_Fvals -mas ${infile}_fdrmask ${infile}_Fthresh
$FSLDIR/bin/run_mesh_utils -m ${infile}.vtk -i ${infile}_Fthresh -o ${infile}_Fthresh.vtk --doVolumeToScalars

